accounts:
  - name: alice
    coins: ["20000000000asfl", "0asfd"]
  - name: bob
    coins: ["10000000000asfl", "0asfd"]
validator:
  name: alice
  staked: "100000000asfl"
client:
  openapi:
    path: "docs/static/openapi.yml"
  vuex:
    path: "vue/src/store"
faucet:
  name: bob
  coins: ["5asfd", "100000asfl"]
