// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: taycanswap/params.proto

package types

import (
	fmt "fmt"
	github_com_cosmos_cosmos_sdk_types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// Params defines the parameters for the module.
type Params struct {
	SwapPreCommition  github_com_cosmos_cosmos_sdk_types.Dec `protobuf:"bytes,1,opt,name=swap_pre_commition,json=swapPreCommition,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Dec" json:"swap_pre_commition" yaml:"swap_pre_commition"`
	SwapPostCommition github_com_cosmos_cosmos_sdk_types.Dec `protobuf:"bytes,2,opt,name=swap_post_commition,json=swapPostCommition,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Dec" json:"swap_post_commition" yaml:"swap_post_commition"`
	SwapRestEndpoint  string                                 `protobuf:"bytes,3,opt,name=swap_rest_endpoint,json=swapRestEndpoint,proto3" json:"swap_rest_endpoint,omitempty" yaml:"swap_rest_endpoint"`
	SwapBaseDenom     string                                 `protobuf:"bytes,4,opt,name=swap_base_denom,json=swapBaseDenom,proto3" json:"swap_base_denom,omitempty" yaml:"swap_base_denom"`
	SwapTokenId       string                                 `protobuf:"bytes,5,opt,name=swap_token_id,json=swapTokenId,proto3" json:"swap_token_id,omitempty" yaml:"swap_token_id"`
	SwapAmount        string                                 `protobuf:"bytes,6,opt,name=swap_amount,json=swapAmount,proto3" json:"swap_amount,omitempty" yaml:"swap_amount"`
	SwapEnabled       bool                                   `protobuf:"varint,7,opt,name=swap_enabled,json=swapEnabled,proto3" json:"swap_enabled,omitempty" yaml:"swap_enabled"`
}

func (m *Params) Reset()      { *m = Params{} }
func (*Params) ProtoMessage() {}
func (*Params) Descriptor() ([]byte, []int) {
	return fileDescriptor_6652740267d97670, []int{0}
}
func (m *Params) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Params) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Params.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Params) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Params.Merge(m, src)
}
func (m *Params) XXX_Size() int {
	return m.Size()
}
func (m *Params) XXX_DiscardUnknown() {
	xxx_messageInfo_Params.DiscardUnknown(m)
}

var xxx_messageInfo_Params proto.InternalMessageInfo

func (m *Params) GetSwapRestEndpoint() string {
	if m != nil {
		return m.SwapRestEndpoint
	}
	return ""
}

func (m *Params) GetSwapBaseDenom() string {
	if m != nil {
		return m.SwapBaseDenom
	}
	return ""
}

func (m *Params) GetSwapTokenId() string {
	if m != nil {
		return m.SwapTokenId
	}
	return ""
}

func (m *Params) GetSwapAmount() string {
	if m != nil {
		return m.SwapAmount
	}
	return ""
}

func (m *Params) GetSwapEnabled() bool {
	if m != nil {
		return m.SwapEnabled
	}
	return false
}

type Supply struct {
	SupplyAmount string `protobuf:"bytes,1,opt,name=SupplyAmount,proto3" json:"SupplyAmount,omitempty"`
}

func (m *Supply) Reset()         { *m = Supply{} }
func (m *Supply) String() string { return proto.CompactTextString(m) }
func (*Supply) ProtoMessage()    {}
func (*Supply) Descriptor() ([]byte, []int) {
	return fileDescriptor_6652740267d97670, []int{1}
}
func (m *Supply) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Supply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Supply.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Supply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Supply.Merge(m, src)
}
func (m *Supply) XXX_Size() int {
	return m.Size()
}
func (m *Supply) XXX_DiscardUnknown() {
	xxx_messageInfo_Supply.DiscardUnknown(m)
}

var xxx_messageInfo_Supply proto.InternalMessageInfo

func (m *Supply) GetSupplyAmount() string {
	if m != nil {
		return m.SupplyAmount
	}
	return ""
}

func init() {
	proto.RegisterType((*Params)(nil), "hupayxcom.taycanswap.taycanswap.Params")
	proto.RegisterType((*Supply)(nil), "hupayxcom.taycanswap.taycanswap.Supply")
}

func init() { proto.RegisterFile("taycanswap/params.proto", fileDescriptor_6652740267d97670) }

var fileDescriptor_6652740267d97670 = []byte{
	// 460 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x53, 0x31, 0x6f, 0xd4, 0x30,
	0x14, 0x4e, 0xe0, 0x38, 0xc0, 0x14, 0x01, 0x6e, 0xd5, 0x86, 0x93, 0x88, 0x2b, 0x0f, 0xa8, 0x03,
	0xbd, 0x0c, 0x1d, 0x90, 0x4e, 0x2c, 0x84, 0x76, 0x40, 0x05, 0xa9, 0x4a, 0x99, 0x58, 0x22, 0x5f,
	0x62, 0x5d, 0xa3, 0x9e, 0x63, 0x2b, 0x76, 0x44, 0x23, 0xf1, 0x23, 0x18, 0x19, 0xf9, 0x39, 0x95,
	0x58, 0x3a, 0x22, 0x86, 0x08, 0xdd, 0xfd, 0x83, 0xfc, 0x02, 0x64, 0x3b, 0xa7, 0xf3, 0xc1, 0xd4,
	0x29, 0xef, 0xfb, 0xde, 0xf7, 0xbe, 0x4f, 0x4f, 0x7e, 0x01, 0x7b, 0x8a, 0x34, 0x19, 0x29, 0xe5,
	0x17, 0x22, 0x22, 0x41, 0x2a, 0xc2, 0xe4, 0x58, 0x54, 0x5c, 0x71, 0x88, 0x2e, 0x6a, 0x41, 0x9a,
	0xab, 0x8c, 0xb3, 0xf1, 0x5a, 0xe2, 0x94, 0xa3, 0x9d, 0x19, 0x9f, 0x71, 0xa3, 0x8d, 0x74, 0x65,
	0xc7, 0xf0, 0xcf, 0x01, 0x18, 0x9e, 0x19, 0x1f, 0xd8, 0x00, 0xa8, 0x85, 0xa9, 0xa8, 0x68, 0x9a,
	0x71, 0xc6, 0x0a, 0x55, 0xf0, 0x32, 0xf0, 0xf7, 0xfd, 0x83, 0x87, 0xf1, 0xe9, 0x75, 0x8b, 0xbc,
	0xdf, 0x2d, 0x7a, 0x39, 0x2b, 0xd4, 0x45, 0x3d, 0x1d, 0x67, 0x9c, 0x45, 0x19, 0x97, 0x8c, 0xcb,
	0xfe, 0x73, 0x28, 0xf3, 0xcb, 0x48, 0x35, 0x82, 0xca, 0xf1, 0x31, 0xcd, 0xba, 0x16, 0x3d, 0x6f,
	0x08, 0x9b, 0x4f, 0xf0, 0xff, 0x8e, 0x38, 0x79, 0xaa, 0xc9, 0xb3, 0x8a, 0xbe, 0x5b, 0x51, 0xf0,
	0x2b, 0xd8, 0xb6, 0x42, 0x2e, 0x95, 0x93, 0x7d, 0xc7, 0x64, 0x7f, 0xb8, 0x75, 0xf6, 0xc8, 0xcd,
	0xde, 0xb0, 0xc4, 0xc9, 0x33, 0x13, 0xce, 0xa5, 0x5a, 0xa7, 0x9f, 0xf6, 0x8b, 0x57, 0x54, 0xaa,
	0x94, 0x96, 0xb9, 0xe0, 0x45, 0xa9, 0x82, 0xbb, 0x26, 0xfc, 0xc5, 0x3f, 0xab, 0x6c, 0x68, 0xfa,
	0x55, 0x12, 0x2a, 0xd5, 0x49, 0x4f, 0xc1, 0x18, 0x3c, 0x31, 0xc2, 0x29, 0x91, 0x34, 0xcd, 0x69,
	0xc9, 0x59, 0x30, 0x30, 0x4e, 0xa3, 0xae, 0x45, 0xbb, 0x8e, 0xd3, 0x5a, 0x80, 0x93, 0xc7, 0x9a,
	0x89, 0x89, 0xa4, 0xc7, 0x1a, 0xc3, 0x37, 0xc0, 0x10, 0xa9, 0xe2, 0x97, 0xb4, 0x4c, 0x8b, 0x3c,
	0xb8, 0x67, 0x1c, 0x82, 0xae, 0x45, 0x3b, 0x8e, 0xc3, 0xaa, 0x8d, 0x93, 0x47, 0x1a, 0x7f, 0xd2,
	0xf0, 0x7d, 0x0e, 0x5f, 0x03, 0x03, 0x53, 0xc2, 0x78, 0x5d, 0xaa, 0x60, 0x68, 0x66, 0x77, 0xbb,
	0x16, 0x41, 0x67, 0xd6, 0x36, 0x71, 0x02, 0x34, 0x7a, 0x6b, 0x00, 0x9c, 0x80, 0x2d, 0xd3, 0xa3,
	0x25, 0x99, 0xce, 0x69, 0x1e, 0xdc, 0xdf, 0xf7, 0x0f, 0x1e, 0xc4, 0x7b, 0x5d, 0x8b, 0xb6, 0x9d,
	0xc9, 0xbe, 0xdb, 0x87, 0x9e, 0x58, 0x34, 0x19, 0x7c, 0xff, 0x81, 0x3c, 0xfc, 0x0a, 0x0c, 0xcf,
	0x6b, 0x21, 0xe6, 0x0d, 0xc4, 0x60, 0xcb, 0x56, 0xd6, 0xdb, 0x9e, 0x51, 0xb2, 0xc1, 0xc5, 0x1f,
	0xaf, 0x17, 0xa1, 0x7f, 0xb3, 0x08, 0xfd, 0x3f, 0x8b, 0xd0, 0xff, 0xb6, 0x0c, 0xbd, 0x9b, 0x65,
	0xe8, 0xfd, 0x5a, 0x86, 0xde, 0xe7, 0x23, 0xe7, 0xa9, 0xed, 0x5d, 0x1f, 0xea, 0xd2, 0x5e, 0xf3,
	0xb9, 0xbe, 0xfd, 0xab, 0xc8, 0xf9, 0x11, 0xcc, 0xdb, 0x4f, 0x87, 0xe6, 0xa2, 0x8f, 0xfe, 0x06,
	0x00, 0x00, 0xff, 0xff, 0x56, 0x80, 0xc6, 0x3f, 0x23, 0x03, 0x00, 0x00,
}

func (m *Params) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Params) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Params) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.SwapEnabled {
		i--
		if m.SwapEnabled {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x38
	}
	if len(m.SwapAmount) > 0 {
		i -= len(m.SwapAmount)
		copy(dAtA[i:], m.SwapAmount)
		i = encodeVarintParams(dAtA, i, uint64(len(m.SwapAmount)))
		i--
		dAtA[i] = 0x32
	}
	if len(m.SwapTokenId) > 0 {
		i -= len(m.SwapTokenId)
		copy(dAtA[i:], m.SwapTokenId)
		i = encodeVarintParams(dAtA, i, uint64(len(m.SwapTokenId)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.SwapBaseDenom) > 0 {
		i -= len(m.SwapBaseDenom)
		copy(dAtA[i:], m.SwapBaseDenom)
		i = encodeVarintParams(dAtA, i, uint64(len(m.SwapBaseDenom)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.SwapRestEndpoint) > 0 {
		i -= len(m.SwapRestEndpoint)
		copy(dAtA[i:], m.SwapRestEndpoint)
		i = encodeVarintParams(dAtA, i, uint64(len(m.SwapRestEndpoint)))
		i--
		dAtA[i] = 0x1a
	}
	{
		size := m.SwapPostCommition.Size()
		i -= size
		if _, err := m.SwapPostCommition.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintParams(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	{
		size := m.SwapPreCommition.Size()
		i -= size
		if _, err := m.SwapPreCommition.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintParams(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *Supply) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Supply) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Supply) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.SupplyAmount) > 0 {
		i -= len(m.SupplyAmount)
		copy(dAtA[i:], m.SupplyAmount)
		i = encodeVarintParams(dAtA, i, uint64(len(m.SupplyAmount)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintParams(dAtA []byte, offset int, v uint64) int {
	offset -= sovParams(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Params) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.SwapPreCommition.Size()
	n += 1 + l + sovParams(uint64(l))
	l = m.SwapPostCommition.Size()
	n += 1 + l + sovParams(uint64(l))
	l = len(m.SwapRestEndpoint)
	if l > 0 {
		n += 1 + l + sovParams(uint64(l))
	}
	l = len(m.SwapBaseDenom)
	if l > 0 {
		n += 1 + l + sovParams(uint64(l))
	}
	l = len(m.SwapTokenId)
	if l > 0 {
		n += 1 + l + sovParams(uint64(l))
	}
	l = len(m.SwapAmount)
	if l > 0 {
		n += 1 + l + sovParams(uint64(l))
	}
	if m.SwapEnabled {
		n += 2
	}
	return n
}

func (m *Supply) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.SupplyAmount)
	if l > 0 {
		n += 1 + l + sovParams(uint64(l))
	}
	return n
}

func sovParams(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozParams(x uint64) (n int) {
	return sovParams(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Params) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowParams
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Params: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Params: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SwapPreCommition", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.SwapPreCommition.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SwapPostCommition", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.SwapPostCommition.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SwapRestEndpoint", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SwapRestEndpoint = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SwapBaseDenom", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SwapBaseDenom = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SwapTokenId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SwapTokenId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SwapAmount", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SwapAmount = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SwapEnabled", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.SwapEnabled = bool(v != 0)
		default:
			iNdEx = preIndex
			skippy, err := skipParams(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthParams
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Supply) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowParams
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Supply: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Supply: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SupplyAmount", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SupplyAmount = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipParams(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthParams
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipParams(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowParams
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowParams
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowParams
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthParams
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupParams
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthParams
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthParams        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowParams          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupParams = fmt.Errorf("proto: unexpected end of group")
)
