// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: taycanswap/params.proto

package types

import (
	fmt "fmt"
	github_com_cosmos_cosmos_sdk_types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// Params defines the parameters for the module.
type Params struct {
	SwapCommition    github_com_cosmos_cosmos_sdk_types.Dec `protobuf:"bytes,1,opt,name=swap_commition,json=swapCommition,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Dec" json:"swap_commition" yaml:"swap_commition"`
	SwapRestEndpoint string                                 `protobuf:"bytes,2,opt,name=swap_rest_endpoint,json=swapRestEndpoint,proto3" json:"swap_rest_endpoint,omitempty" yaml:"swap_rest_endpoint"`
	SwapBaseDenom    string                                 `protobuf:"bytes,3,opt,name=swap_base_denom,json=swapBaseDenom,proto3" json:"swap_base_denom,omitempty" yaml:"swap_base_denom"`
	SwapTokenId      string                                 `protobuf:"bytes,4,opt,name=swap_token_id,json=swapTokenId,proto3" json:"swap_token_id,omitempty" yaml:"swap_token_id"`
	SwapEnabled      bool                                   `protobuf:"varint,5,opt,name=swap_enabled,json=swapEnabled,proto3" json:"swap_enabled,omitempty" yaml:"swap_enabled"`
}

func (m *Params) Reset()      { *m = Params{} }
func (*Params) ProtoMessage() {}
func (*Params) Descriptor() ([]byte, []int) {
	return fileDescriptor_6652740267d97670, []int{0}
}
func (m *Params) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Params) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Params.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Params) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Params.Merge(m, src)
}
func (m *Params) XXX_Size() int {
	return m.Size()
}
func (m *Params) XXX_DiscardUnknown() {
	xxx_messageInfo_Params.DiscardUnknown(m)
}

var xxx_messageInfo_Params proto.InternalMessageInfo

func (m *Params) GetSwapRestEndpoint() string {
	if m != nil {
		return m.SwapRestEndpoint
	}
	return ""
}

func (m *Params) GetSwapBaseDenom() string {
	if m != nil {
		return m.SwapBaseDenom
	}
	return ""
}

func (m *Params) GetSwapTokenId() string {
	if m != nil {
		return m.SwapTokenId
	}
	return ""
}

func (m *Params) GetSwapEnabled() bool {
	if m != nil {
		return m.SwapEnabled
	}
	return false
}

func init() {
	proto.RegisterType((*Params)(nil), "hupayxcom.taycanswap.taycanswap.Params")
}

func init() { proto.RegisterFile("taycanswap/params.proto", fileDescriptor_6652740267d97670) }

var fileDescriptor_6652740267d97670 = []byte{
	// 380 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x52, 0xbd, 0x6e, 0xea, 0x30,
	0x18, 0x4d, 0x2e, 0x5c, 0x74, 0x6f, 0xee, 0xaf, 0x52, 0x5a, 0x52, 0xa4, 0xc6, 0x28, 0x43, 0xc5,
	0x42, 0x32, 0xb0, 0xa1, 0x4e, 0x29, 0xa8, 0xaa, 0xaa, 0x4a, 0x55, 0xda, 0xa9, 0x4b, 0xe4, 0x24,
	0x16, 0x44, 0x60, 0x3b, 0xc2, 0x46, 0x25, 0x8f, 0xd0, 0xad, 0x63, 0xc7, 0x3e, 0x0e, 0x23, 0x63,
	0xd5, 0x21, 0xaa, 0xe0, 0x0d, 0xf2, 0x04, 0x95, 0x9d, 0x20, 0xc2, 0xe4, 0xef, 0x9c, 0xef, 0x7c,
	0xc7, 0x96, 0xcf, 0xa7, 0xb5, 0x38, 0x4c, 0x43, 0x48, 0xd8, 0x13, 0x4c, 0x9c, 0x04, 0xce, 0x21,
	0x66, 0x76, 0x32, 0xa7, 0x9c, 0xea, 0x60, 0xb2, 0x48, 0x60, 0xba, 0x0c, 0x29, 0xb6, 0xf7, 0x92,
	0x4a, 0xd9, 0x6e, 0x8e, 0xe9, 0x98, 0x4a, 0xad, 0x23, 0xaa, 0x62, 0xcc, 0x7a, 0xae, 0x69, 0x8d,
	0x3b, 0xe9, 0xa3, 0x13, 0xed, 0xaf, 0x10, 0xfa, 0x21, 0xc5, 0x38, 0xe6, 0x31, 0x25, 0x86, 0xda,
	0x51, 0xbb, 0x3f, 0xdd, 0xab, 0x55, 0x06, 0x94, 0x8f, 0x0c, 0x9c, 0x8f, 0x63, 0x3e, 0x59, 0x04,
	0x76, 0x48, 0xb1, 0x13, 0x52, 0x86, 0x29, 0x2b, 0x8f, 0x1e, 0x8b, 0xa6, 0x0e, 0x4f, 0x13, 0xc4,
	0xec, 0x21, 0x0a, 0xf3, 0x0c, 0x1c, 0xa7, 0x10, 0xcf, 0x06, 0xd6, 0xa1, 0x9b, 0xe5, 0xfd, 0x11,
	0xc4, 0xe5, 0x0e, 0xeb, 0x37, 0x9a, 0x2e, 0x15, 0x73, 0xc4, 0xb8, 0x8f, 0x48, 0x94, 0xd0, 0x98,
	0x70, 0xe3, 0x9b, 0xbc, 0xf3, 0x2c, 0xcf, 0xc0, 0x69, 0xc5, 0xe5, 0x40, 0x63, 0x79, 0xff, 0x05,
	0xe9, 0x21, 0xc6, 0x47, 0x25, 0xa5, 0xbb, 0xda, 0x3f, 0x29, 0x0c, 0x20, 0x43, 0x7e, 0x84, 0x08,
	0xc5, 0x46, 0x4d, 0x3a, 0xb5, 0xf3, 0x0c, 0x9c, 0x54, 0x9c, 0xf6, 0x82, 0xf2, 0x41, 0x2e, 0x64,
	0x68, 0x28, 0xb0, 0x7e, 0xa1, 0x49, 0xc2, 0xe7, 0x74, 0x8a, 0x88, 0x1f, 0x47, 0x46, 0x5d, 0x3a,
	0x18, 0x79, 0x06, 0x9a, 0x15, 0x87, 0x5d, 0xdb, 0xf2, 0x7e, 0x09, 0xfc, 0x20, 0xe0, 0x75, 0xa4,
	0x0f, 0xb4, 0xdf, 0xb2, 0x8d, 0x08, 0x0c, 0x66, 0x28, 0x32, 0xbe, 0x77, 0xd4, 0xee, 0x0f, 0xb7,
	0x95, 0x67, 0xe0, 0xa8, 0x32, 0x5c, 0x76, 0xcb, 0xd9, 0x51, 0x81, 0x06, 0xf5, 0xd7, 0x37, 0xa0,
	0xb8, 0xb7, 0xab, 0x8d, 0xa9, 0xae, 0x37, 0xa6, 0xfa, 0xb9, 0x31, 0xd5, 0x97, 0xad, 0xa9, 0xac,
	0xb7, 0xa6, 0xf2, 0xbe, 0x35, 0x95, 0xc7, 0x7e, 0xe5, 0xeb, 0x8b, 0x9c, 0x7b, 0xa2, 0x2c, 0xd2,
	0xbd, 0x17, 0xbb, 0xb0, 0x74, 0x2a, 0x8b, 0x21, 0xb3, 0x08, 0x1a, 0x32, 0xe1, 0xfe, 0x57, 0x00,
	0x00, 0x00, 0xff, 0xff, 0xd1, 0x47, 0xf7, 0x77, 0x33, 0x02, 0x00, 0x00,
}

func (m *Params) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Params) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Params) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.SwapEnabled {
		i--
		if m.SwapEnabled {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x28
	}
	if len(m.SwapTokenId) > 0 {
		i -= len(m.SwapTokenId)
		copy(dAtA[i:], m.SwapTokenId)
		i = encodeVarintParams(dAtA, i, uint64(len(m.SwapTokenId)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.SwapBaseDenom) > 0 {
		i -= len(m.SwapBaseDenom)
		copy(dAtA[i:], m.SwapBaseDenom)
		i = encodeVarintParams(dAtA, i, uint64(len(m.SwapBaseDenom)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.SwapRestEndpoint) > 0 {
		i -= len(m.SwapRestEndpoint)
		copy(dAtA[i:], m.SwapRestEndpoint)
		i = encodeVarintParams(dAtA, i, uint64(len(m.SwapRestEndpoint)))
		i--
		dAtA[i] = 0x12
	}
	{
		size := m.SwapCommition.Size()
		i -= size
		if _, err := m.SwapCommition.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintParams(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func encodeVarintParams(dAtA []byte, offset int, v uint64) int {
	offset -= sovParams(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Params) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.SwapCommition.Size()
	n += 1 + l + sovParams(uint64(l))
	l = len(m.SwapRestEndpoint)
	if l > 0 {
		n += 1 + l + sovParams(uint64(l))
	}
	l = len(m.SwapBaseDenom)
	if l > 0 {
		n += 1 + l + sovParams(uint64(l))
	}
	l = len(m.SwapTokenId)
	if l > 0 {
		n += 1 + l + sovParams(uint64(l))
	}
	if m.SwapEnabled {
		n += 2
	}
	return n
}

func sovParams(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozParams(x uint64) (n int) {
	return sovParams(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Params) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowParams
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Params: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Params: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SwapCommition", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.SwapCommition.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SwapRestEndpoint", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SwapRestEndpoint = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SwapBaseDenom", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SwapBaseDenom = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SwapTokenId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SwapTokenId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SwapEnabled", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.SwapEnabled = bool(v != 0)
		default:
			iNdEx = preIndex
			skippy, err := skipParams(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthParams
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipParams(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowParams
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowParams
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowParams
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthParams
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupParams
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthParams
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthParams        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowParams          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupParams = fmt.Errorf("proto: unexpected end of group")
)
